fun main(args: Array<String>) {
//
//    // Test LinkedList
//    var ll: LinkedList<Int> = LinkedList()
//    ll.add(5)
//    ll.add(10)
//    ll.add(20)
//    ll.add(40)
//    ll.print()
//    println(ll.size())
//    ll.remove(1)
//    ll.print()
//    println(ll.size())
//    println(ll.get(1).toString())
//
//    // Test Stack
//    var stack: Stack<Int> = Stack()
//    stack.push(1)
//    stack.push(2)
//    stack.push(3)
//    stack.push(4)
//    stack.print()
//    stack.pop()
//    stack.print()
//    stack.empty()

//    // Test Queue
//    var queue: Queue<Int> = Queue()
//    queue.add(10)
//    queue.add(20)
//    queue.add(30)
//    queue.add(40)
//    queue.add(50)
//    queue.print()
//    println(queue.peek())
//    queue.remove()
//    queue.print()

//    // Test HashMap
//    val hashMap: HashMap<Int, String> = HashMap(10)
//    hashMap.put(1, "One")
//    hashMap.put(2, "Two")
//    hashMap.put(3, "Three")
//    println(hashMap.get(2))
//    println(hashMap.containsKey(0))
//    println(hashMap.containsKey(1))
//    println(hashMap.containsValue("Zero"))
//    println(hashMap.containsValue("One"))
//    println(hashMap.size())
//    println(hashMap.remove(2))
//    println(hashMap.size())

//    // Test BinarySearchTree
//    val bst: BinarySearchTree<Int> = BinarySearchTree()
//    bst.insert(56)
//    bst.insert(92)
//    bst.insert(44)
//    bst.insert(1)
//    bst.insert(49)
//    bst.insert(15)
//    bst.insert(47)
//    bst.insert(62)
//    bst.insert(74)
//    bst.insert(63)
//    bst.preOrder()
//    println()
//    bst.inOrder()
//    println()
//    bst.postOrder()
//    bst.remove(44)
//    println()
//    bst.inOrder()
}
